"use client"
import React from "react"
import { Epilogue } from "next/font/google"
import { ConfigProvider, Layout, theme } from "antd"
const { Content } = Layout
import SideBar from "@/component/SideBar"
import HeaderBar from "@/component/Header"
import "./globals.css"
import { store, persistor } from "@/redux"
import { Provider } from "react-redux"
import { PersistGate } from "redux-persist/integration/react"

const epilogue = Epilogue({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }) => {
  const segments = children.props.childProp.segment
  const path_except = ["", "signin", "signup"]
  const is_except = path_except.findIndex((el) => el == segments)

  return (
    <html lang="en">
      <body className={epilogue.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <ConfigProvider theme={theme}>
              {is_except !== -1 ? (
                children
              ) : (
                <Layout className="layout-wrapper">
                  <SideBar />
                  <Layout>
                    <HeaderBar />
                    <Content className="content">{children}</Content>
                  </Layout>
                </Layout>
              )}
            </ConfigProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout
